language: python
python:
- '2.7'
install: pip install -q -r requirements.txt
script: sphinx-build -nW -b html -d _build/doctrees . _build/html
before_deploy: perl -i -ple 'if (/__badcode__/) { s/(<span class="nx">)?__badcode__(<\/span>)?//; s/highlight-javascript/highlight-javascript gjsg_badcode/; }' _build/html/index.html
deploy:
  provider: s3
  access_key_id:
    secure: gLXX7f/lGZjUX4MZaEECylTEmPtErXAXTQ1Th3yfAXdRYf7Nj1UfMaHOo6jsVxwIuaS8VYXhts0LyggasgYG34Mifq4LeV4q8WsTR6CiPvoYGwgB1lnvUXmbHSAEb+jxnTYF1LFc61M+gU4h3naJqDJ1dbXP+UBPHTa4TVim/s0=
  secret_access_key:
    secure: Q1joAA+xhdpBzIeasAFRF7SI3mGl3InaX8OEfz57NsG2YvxtpIZeJ2omLYiA7dPgdgep5t6nn4Ld2khnw3lI+XGfBFzcJlOr7hTyuzLGcViSbs1fzRERnj+zquf+n6OKuAKrAcZOEzXAV7XEJziy5dzIDSFjRrvbk4eMdtasMZ8=
  bucket: cou929.nu
  skip_cleanup: true
  endpoint: cou929.nu.s3-website-ap-northeast-1.amazonaws.com
  region: ap-northeast-1
  local-dir: _build/html/
  upload-dir: data/google_javascript_style_guide
