language: python
python:
- '2.7'
install: pip install -q -r requirements.txt
script: sphinx-build -nW -b html -d _build/doctrees . _build/html
before_deploy: perl -i -ple 'if (/__badcode__/) { s/(<span class="nx">)?__badcode__(<\/span>)?//; s/highlight-javascript/highlight-javascript gjsg_badcode/; }' _build/html/index.html
deploy:
  provider: s3
  access_key_id:
    secure: Z6ScwOL0wVWbHucjllueun7BaQLOj/sQNa8vTgGOWq5U1ZllWQg+X7DqoopEkbj+h6CCpx/73FCGNm/5ChU+n/3L6SvJsbimcJ5O78NgDKi1RJ27jeaLLjPFsfsrshKrBaGENTbfG8Q7QMc7015//0uVF7qpH0nldwBspcSekKQ=
  secret_access_key:
    secure: Kibqr9yvPuSpia/KtM0N6SQT20MINkj3pffICb4EtCXFitaIxp1GvZC/nUcs3+U/Db0UlApIZD7Ko7EVB//BmNDkQdpkPAfXLsZjFHGlf7mPZuohF7Nq2aZpSquSwajuCCWYNcZ9x86T5ngTdxHH7vWmtXOCPLIdVgEZQz3Exqk=
  bucket: cou929.nu
  skip_cleanup: true
  endpoint: cou929.nu.s3-website-ap-northeast-1.amazonaws.com
  region: ap-northeast-1
  local-dir: _build/html/
  upload-dir: data/google_javascript_style_guide
